name: Python Tests

permissions:
  contents: read
  checks: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy scipy scikit-learn xgboost

    - name: Cache downloaded data
      id: cache-data
      uses: actions/cache@v4
      with:
        path: data
        key: ${{ runner.os }}-data
  
    - name: Download Data
      run: |
        mkdir -p data
        cd data
        wget -q ${{ secrets.DOWNLOAD_URL }}
        wget -q ${{ secrets.DOWNLOAD_URL_CUE }}
        cd ..
        for file in data/*; do ln -s "$file" .; done

    - name: Run tests
      run: python -m unittest discover -s .
